DoDucHoa/CapstoneProject

PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Service/AuthService.cs
PawNClaw.Backend/PawNClaw.Data/Database/Account.cs
PawNClaw.Backend/PawNClaw.Data/Database/Admin.cs
PawNClaw.Backend/PawNClaw.Data/Database/ApplicationDbContext.cs
PawNClaw.Backend/PawNClaw.Data/Database/Customer.cs
PawNClaw.Backend/PawNClaw.Data/Database/Owner.cs
PawNClaw.Backend/PawNClaw.Data/Database/Staff.cs
PawNClaw.Backend/PawNClaw.Data/Database/SupplyType.cs
PawNClaw.Backend/PawNClaw.Data/Database/VoucherType.cs
PawNClaw.Backend/PawNClaw.Data/Helper/LoginViewModel.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ICustomerRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IOwnerRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IStaffRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/AdminRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CustomerRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/OwnerRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/StaffRepository.cs

- Update new Entities from Database
- Complete Login Function
- Not tested yet

[Backend]-Login Function

---

PawNClaw.Backend/PawNClaw.Business/Service/AuthService.cs

- Have a bug but it auto fix. Don't know why it happened and how it fixed????

[Backend]-Fix Login

---

PawNClaw.Backend/PawNClaw.API/Controllers/AccountsController.cs
PawNClaw.Backend/PawNClaw.API/Controllers/AuthsController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/AccountService.cs
PawNClaw.Backend/PawNClaw.Business/Services/AdminService.cs
PawNClaw.Backend/PawNClaw.Business/Services/AuthService.cs
PawNClaw.Backend/PawNClaw.Data/Helper/PagedList.cs
PawNClaw.Backend/PawNClaw.Data/Helper/PagingParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/AccountRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/AdminRequestParameter.cs

- Account Api need to check role update delete.
- Admin Api completed Service but not created Api.
- Add paging.
- Change SignIn from [FromQuery] to [FromBody].
- Change Email/Password to Email

[Backend]-Account and Admin Api

---

PawNClaw.Backend/PawNClaw.API/Controllers/AuthsController.cs
PawNClaw.Backend/PawNClaw.API/PawNClaw.API.csproj
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Database/ApplicationDbContext.cs
PawNClaw.Backend/PawNClaw.Data/Database/PetCenter.cs
PawNClaw.Backend/PawNClaw.Data/Database/Staff.cs
PawNClaw.Backend/PawNClaw.Data/Helper/SignUpRequestModel.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ILocationRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetCenterRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/LocationRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/PetCenterRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/PetRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/LocationRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetCenterRepository.cs

- Search Function hasn't completed yet.
- Sign Up Parameter from Query to Body
- Fix Include not work

[Backend]-Search Function

---

PawNClaw.Backend/PawNClaw.API/Controllers/PetCentersController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Helper/SearchRequestModel.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ICageRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetCenterRepository.cs

- Complete Search Function but not TEST yet.

[Backend]-Complete Search Function

---

PawNClaw.Backend/PawNClaw.API/Controllers/AccountsController.cs
PawNClaw.Backend/PawNClaw.API/Controllers/AdminsController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/AdminService.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetCenterRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetCenterRepository.cs

- API Fixed
- Authorize on Swagger
- Cannot optimize Search Function

[Backend]-Fix API and Add Authorize For Swagger

---

PawNClaw.Backend/PawNClaw.API/Controllers/AdminsController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/AuthService.cs
PawNClaw.Backend/PawNClaw.Data/Helper/LoginViewModel.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPhotoRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PhotoRepository.cs

- Sign In add new field Url
- API for Admin

[Backend]-Sign In Fix and API Admin Fix

---

PawNClaw.Backend/PawNClaw.API/Controllers/PetController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/AdminService.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetRepository.cs

- Add new function get pet by customer Id
- Admin only get Mod (required includeProperties)

[Backend]-Pet Controller and Service

---

PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/BrandService.cs
PawNClaw.Backend/PawNClaw.Business/Services/OwnerService.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetCenterService.cs
PawNClaw.Backend/PawNClaw.Business/Services/StaffServicecs.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBrandRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BrandRepository.cs

- Add new services: Brand, Owner, Pet Center, Staff.
- Add new repository: Brand.

[Backend]-Services and Repository

---

PawNClaw.Backend/PawNClaw.Business/Services/PetCenterService.cs
PawNClaw.Backend/PawNClaw.Data/DataObject/PetCenterData.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetCenterRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetCenterRepository.cs

- This update is remove Rating Count from PetCenters class. Create new class with fields is PetCenters and RatingCount.

[Backend]-Adding Rating Count into PetCenters response

---

PawNClaw.Backend/PawNClaw.API/Controllers/BookingsController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingService.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetCenterService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetBookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IServiceOrderRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ISupplyOrderRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ISupplyRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/BookingCreateParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetBookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/Repository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/ServiceOrderRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/SupplyOrderRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/SupplyRepository.cs

- Create Booking with Create Booking Detail, Pet Booking Detail, Service Order, Supply Order.
- Have transaction for Create Booking flow

[Backend]-Create Booking Done

---

PawNClaw.Backend/PawNClaw.API/Controllers/PetHealthHistorySerivce.cs
PawNClaw.Backend/PawNClaw.API/Controllers/PetHealthHistorysController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetHealthHistoryService.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetHealthHistoryRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/PetHealthHistoryParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/PetRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetHealthHistoryRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetRepository.cs

[Backend]-Create Pet Health History

---

PawNClaw.Backend/PawNClaw.Business/Services/BookingService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ICageRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageRepository.cs

- Auto Sum
- Check pet size with cage size when create

[Backend]-Auto Sum Price

---

PawNClaw.Backend/PawNClaw.API/Controllers/CageTypesController.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingService.cs
PawNClaw.Backend/PawNClaw.Business/Services/CageTypeService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ICageTypeRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/PetRequestParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageTypeRepository.cs

- Get Cage Valid with Pet Size and Booking Time. (API CageType GET staff-booking)
- Fix Create Booking check if cage is used in the booking time

[Backend]-Get Cage For Re-Booking

---

PawNClaw.Backend/PawNClaw.API/Controllers/BookingDetailsController.cs
PawNClaw.Backend/PawNClaw.API/Controllers/CageTypesController.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingDetailService.cs
PawNClaw.Backend/PawNClaw.Business/Services/CageTypeService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Interface/ICageTypeRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/BookingCreateParameter.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/BookingDetailParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingDetailRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageTypeRepository.cs

- Get Cage Valid With Pet Size.
- Update Cage Of Booking Detail With Check Size Pet And Cage In Backend
- Only Get ONE Cage Type For One Single(Multiple) Pet To Cage
- Update ONE Booking Detail Each Call API

[Backend]-Done Update Booking Detail Flow

---

PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Repository/CageRepository.cs

- Fix Search Always True
- Fix Get Cage Type

[Backend]-Fix Search

---

PawNClaw.Backend/PawNClaw.API/Controllers/ValuesController.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs

- Fix Response For Staff Get Booking By Id On Mobile

[Backend]-Fix Response For Get Booking

---

PawNClaw.Backend/PawNClaw.Data/Database/Booking.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs

- Get Cage Type Name
- Get Customer Phone
- Add Total Supply And Total Service

[Backend]-Update Get Booking

---

PawNClaw.Backend/PawNClaw.API/Controllers/BookingDetailsController.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingDetailService.cs

[Backend]-Fix Update Booking Detail

---

PawNClaw.Backend/PawNClaw.API/Controllers/BookingActivitiesController.cs
PawNClaw.Backend/PawNClaw.API/Controllers/BookingsController.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingActivityService.cs
PawNClaw.Backend/PawNClaw.Data/Helper/TimeHelper.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IBookingRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/BookingActivityParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs

-Get Activity Today
-Create Activity after confirm
-Update Activity

[Backend]-Create Activity

---

PawNClaw.Backend/PawNClaw.API/Controllers/CageTypesController.cs
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/AccountService.cs
PawNClaw.Backend/PawNClaw.Business/Services/CageTypeService.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IFoodScheduleRepository.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/CageTypeParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/AccountRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/FoodScheduleRepository.cs

- Create Food Schedule when create Cage Type.
- Return End Booking when Check.
- Get Account with Cus, Own, Ad, Staff.

[Backend]-CRUD

---

PawNClaw.Backend/PawNClaw.API/Controllers/ValuesController.cs
PawNClaw.Backend/PawNClaw.API/PawNClaw.API.csproj
PawNClaw.Backend/PawNClaw.API/Startup.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingDetailService.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingService.cs
PawNClaw.Backend/PawNClaw.Business/Services/PolicyService.cs
PawNClaw.Backend/PawNClaw.Business/Services/ServiceOrderService.cs
PawNClaw.Backend/PawNClaw.Business/Services/SupplyOrderService.cs

[Backend]-Fix Price with Discount for Booking

---

PawNClaw.Backend/PawNClaw.API/Controllers/PetCentersController.cs
PawNClaw.Backend/PawNClaw.Business/Services/PetCenterService.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Helper/GetCenterByIdRequestModel.cs
PawNClaw.Backend/PawNClaw.Data/Interface/IPetCenterRepository.cs
PawNClaw.Backend/PawNClaw.Data/Repository/PetCenterRepository.cs

- Change check-center
- Change get-center-detail

[Backend]-Change Request API

---

PawNClaw.Backend/PawNClaw.API/Controllers/RevenueReportOwnersController.cs
PawNClaw.Backend/PawNClaw.Business/Services/BookingService.cs
PawNClaw.Backend/PawNClaw.Business/Services/RevenueReportOwnerService.cs
PawNClaw.Backend/PawNClaw.Business/Services/SearchService.cs
PawNClaw.Backend/PawNClaw.Data/Parameter/RevenueParameter.cs
PawNClaw.Backend/PawNClaw.Data/Repository/BookingRepository.cs

- Fix Search
- Fix Confirm booking

[Backend]-Fix Dashboard
